#!/usr/bin/env bash
set -eu

# Note: to use lldb, compile with -O0 -g, run `lldb ./$OUT`, and type "process launch -i in.txt".
COPTS=(
    --std=c++20
    -O2
    -Wall
    -Wextra
    # -Wl,-stack_size -Wl,100000000 # Large stack on Mac.
    # -g -fno-omit-frame-pointer -O1 -fsanitize=address,undefined # Debugging.
    # -fsanitize=memory # Unsupported on Apple Silicon.
)

# Collect extra compiler flags.
while [[ $# -gt 1 ]]; do
    COPTS+=("$1")
    shift
done

if [[ $# -ne 1 || "$1" == -* ]]; then
    echo "Usage: $0 [copts...] <src>"
    exit 1
fi

OUT="${1%.cpp}"
g++ "${COPTS[@]}" -o "$OUT" "$OUT.cpp"
