#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Please provide a file to compile"
    exit 1
fi

OUT=${1%.cpp}
g++ ${OUT}.cpp --std=c++17 -O2 -o $OUT
# Note: can increase stack size on Mac with -Wl,-stack_size -Wl,100000000
